//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inver.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComercializadoraSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComercializadoraSet()
        {
            this.RecoleccionSet = new HashSet<RecoleccionSet>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int SiembraId { get; set; }
        public short Comision { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecoleccionSet> RecoleccionSet { get; set; }
        public virtual SiembraSet SiembraSet { get; set; }
    }
}
