//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inver.Entidad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inverEntities : DbContext
    {
        public inverEntities()
            : base("name=inverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClasificacionSet> ClasificacionSet { get; set; }
        public virtual DbSet<ComercializadoraSet> ComercializadoraSet { get; set; }
        public virtual DbSet<GastoGeneralSet> GastoGeneralSet { get; set; }
        public virtual DbSet<GastosSiembraSet> GastosSiembraSet { get; set; }
        public virtual DbSet<JornalSet> JornalSet { get; set; }
        public virtual DbSet<ProveedorSet> ProveedorSet { get; set; }
        public virtual DbSet<RecoleccionSet> RecoleccionSet { get; set; }
        public virtual DbSet<RiegoSet> RiegoSet { get; set; }
        public virtual DbSet<SiembraSet> SiembraSet { get; set; }
        public virtual DbSet<SueltaSet> SueltaSet { get; set; }
        public virtual DbSet<TrabajadorSet> TrabajadorSet { get; set; }
        public virtual DbSet<TratamientoSet> TratamientoSet { get; set; }
        public virtual DbSet<UsuarioSet> UsuarioSet { get; set; }
    }
}
