//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inver.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoleccionSet
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public short Kilos { get; set; }
        public short Bultos { get; set; }
        public decimal Precio { get; set; }
        public bool Cobrado { get; set; }
        public int SiembraId { get; set; }
        public int ComercializadoraId { get; set; }
        public int ClasificacionId { get; set; }
    
        public virtual ClasificacionSet ClasificacionSet { get; set; }
        public virtual ComercializadoraSet ComercializadoraSet { get; set; }
        public virtual SiembraSet SiembraSet { get; set; }
    }
}
