//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inver.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiembraSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiembraSet()
        {
            this.ClasificacionSet = new HashSet<ClasificacionSet>();
            this.ComercializadoraSet = new HashSet<ComercializadoraSet>();
            this.GastosSiembraSet = new HashSet<GastosSiembraSet>();
            this.RecoleccionSet = new HashSet<RecoleccionSet>();
            this.RiegoSet = new HashSet<RiegoSet>();
            this.SueltaSet = new HashSet<SueltaSet>();
            this.TratamientoSet = new HashSet<TratamientoSet>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Cultivo { get; set; }
        public short Superficie { get; set; }
        public short Plantas { get; set; }
        public bool Activa { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public Nullable<int> UsuarioId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClasificacionSet> ClasificacionSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComercializadoraSet> ComercializadoraSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastosSiembraSet> GastosSiembraSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecoleccionSet> RecoleccionSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiegoSet> RiegoSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SueltaSet> SueltaSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TratamientoSet> TratamientoSet { get; set; }
        public virtual UsuarioSet UsuarioSet { get; set; }
    }
}
