//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inver.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabajadorSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrabajadorSet()
        {
            this.GastoGeneralSet = new HashSet<GastoGeneralSet>();
            this.GastosSiembraSet = new HashSet<GastosSiembraSet>();
            this.JornalSet = new HashSet<JornalSet>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> UsuarioId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastoGeneralSet> GastoGeneralSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastosSiembraSet> GastosSiembraSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JornalSet> JornalSet { get; set; }
        public virtual UsuarioSet UsuarioSet { get; set; }
    }
}
